name: CD

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  test_vulnerability_analysis:
    uses: ./.github/workflows/execute-tests.yaml

  version:
    uses: coreeng/p2p/.github/workflows/p2p-version.yaml@v1
    needs: [test_vulnerability_analysis]
    secrets:
      git-token: ${{ secrets.GITHUB_TOKEN }}
